openapi: 3.0.0
info:
  title: ShadowFax
  contact: {}
  version: '1.0'
servers:
- url: https://api.chetanpareek.tech
  variables: {}
paths:
  /:
    get:
      tags:
      - Misc
      summary: home route
      operationId: homeroute
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/shop/list_shop:
    post:
      tags:
      - Misc
      summary: list_shop
      operationId: list_shop
      parameters:
      - name: username
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: swarnabha1499
      - name: email
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: sd2001@gmail.com
      - name: phone
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int64
          example: 7891497867
      - name: fname
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: swarnabha
      - name: lname
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: dalla
      - name: shop_name
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: Swarnabha Kiranna Store
      - name: latitude
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: number
          format: double
          example: 28.731576
      - name: longitude
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: number
          format: double
          example: 77.03189
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/user/get_all_products:
    get:
      tags:
      - Misc
      summary: get_all_products
      operationId: get_all_products
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/user/get_all_tags:
    get:
      tags:
      - Misc
      summary: get_all_tags
      operationId: get_all_tags
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/user/create_user:
    post:
      tags:
      - Misc
      summary: register new user
      operationId: registernewuser
      parameters:
      - name: username
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: cp99says
      - name: email
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: cp99says@gmail.com
      - name: phone
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int64
          example: 7417417894
      - name: fname
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: 'chetan '
      - name: lname
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: pareek
      - name: latitude
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: number
          format: double
          example: 28.72977
      - name: longitude
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: number
          format: double
          example: 77.042815
      - name: location
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: Begum Pur, North west Delhi
      - name: city
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: delhi
      - name: state
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: delhi
      - name: country
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: india
      - name: pincode
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 110001
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/user/get_product_using_inc_id:
    get:
      tags:
      - Misc
      summary: get_products_using_inc_id
      operationId: get_products_using_inc_id
      parameters:
      - name: inc_id
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 4
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/shop/list_products:
    post:
      tags:
      - Misc
      summary: list_products
      operationId: list_products
      parameters:
      - name: product_name
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: Otrivin
      - name: mrp
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 80
      - name: image_address
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: https://cdn01.pharmeasy.in/dam/products_otc/348028/otrivin-oxy-fast-adult-relief-nasalspray-1.jpg
      - name: shop_id
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 1
      - name: tags_string
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: drinks,protein
      - name: quantity
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 50
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/shop/get_products_by_shop_id:
    get:
      tags:
      - Misc
      summary: get_products_by_shop_id
      operationId: get_products_by_shop_id
      parameters:
      - name: id
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 1
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/rider/post_rider_details:
    post:
      tags:
      - Misc
      summary: post rider details
      operationId: postriderdetails
      parameters:
      - name: username
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: raghav1499
      - name: email
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: ra58@srmist.edu.in
      - name: phone
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int64
          example: 7891497865
      - name: fname
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: raghav
      - name: lname
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: aggarwal
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/rider/set_fcm_token:
    patch:
      tags:
      - Misc
      summary: set fcm token
      operationId: setfcmtoken
      parameters:
      - name: token
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: fvpubE_xT_K-LJVU4l3hU-:APA91bHOA1jE-XkHGBONL2VEVLLOp_uFNcDzVAR5xLKJtYb9Qty3XGrRIL5gMq-zSdAOEuvYlEiKMfQPTn0O4RFGX1vH_319p0i25Q4EzuGDlztEvvWC7VP0LcnZEGuFKqoys3IeH1of
      - name: inc_id
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 1
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/rider/set_current_coordinates:
    patch:
      tags:
      - Misc
      summary: patch latitudes and longitudes
      operationId: patchlatitudesandlongitudes
      parameters:
      - name: latitude
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: number
          format: double
          example: 28.737707
      - name: longitude
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: number
          format: double
          example: 77.007395
      - name: inc_id
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 1
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/shop/set_shop_token:
    patch:
      tags:
      - Misc
      summary: set shop token
      operationId: setshoptoken
      parameters:
      - name: token
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: random token hai bhai
      - name: inc_id
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 1
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/user/place_order:
    post:
      tags:
      - Misc
      summary: place order
      operationId: placeorder
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/placeorderrequest'
            example:
              orders:
              - inc_id: 4
                quantity: 5
              - inc_id: 7
                quantity: 10
              inc_id: 6
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/rider/get_details_using_username:
    get:
      tags:
      - Misc
      summary: get rider details using username
      operationId: getriderdetailsusingusername
      parameters:
      - name: username
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: raghav1399
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/rider/get_all_riders:
    get:
      tags:
      - Misc
      summary: get all riders
      operationId: getallriders
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/rider/get_active_orders:
    get:
      tags:
      - Misc
      summary: check active orders
      operationId: checkactiveorders
      parameters:
      - name: username
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: raghav1299
      - name: active_orders
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 1
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/rider/set_order_delivered:
    patch:
      tags:
      - Misc
      summary: set order delivered
      operationId: setorderdelivered
      parameters:
      - name: username
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: raghav1399
      - name: inc_id
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 2
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/user/get_user_details_by_username:
    get:
      tags:
      - Misc
      summary: get user details by username
      operationId: getuserdetailsbyusername
      parameters:
      - name: username
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: cp99says
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/user/get_order_history_of_user:
    get:
      tags:
      - Misc
      summary: get order  history of user
      operationId: getorderhistoryofuser
      parameters:
      - name: inc_id
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 1
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/user/set_user_fcm_token:
    patch:
      tags:
      - Misc
      summary: set user fcm token
      operationId: setuserfcmtoken
      parameters:
      - name: token
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: ram ka test token
      - name: inc_id
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 6
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/shop/show_active_orders:
    get:
      tags:
      - Misc
      summary: shop active orders
      operationId: shopactiveorders
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/shop/set_order_delivered:
    patch:
      tags:
      - Misc
      summary: set order delivered
      operationId: Patchsetorderdelivered
      parameters:
      - name: order_id
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: GwNwYdX8r48iVQvv1B_HF
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
components:
  schemas:
    placeorderrequest:
      title: placeorderrequest
      required:
      - orders
      - inc_id
      type: object
      properties:
        orders:
          type: array
          items:
            $ref: '#/components/schemas/Order'
          description: ''
        inc_id:
          type: integer
          format: int32
      example:
        orders:
        - inc_id: 4
          quantity: 5
        - inc_id: 7
          quantity: 10
        inc_id: 6
    Order:
      title: Order
      required:
      - inc_id
      - quantity
      type: object
      properties:
        inc_id:
          type: integer
          format: int32
        quantity:
          type: integer
          format: int32
      example:
        inc_id: 4
        quantity: 5
tags:
- name: Misc
  description: ''