openapi: 3.0.0
info:
  title: ShadowFax
  contact: {}
  version: '1.0'
servers:
- url: https://api.chetanpareek.tech
  variables: {}
paths:
  /:
    get:
      tags:
      - Misc
      summary: home route
      operationId: homeroute
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/get_all_products:
    get:
      tags:
      - Misc
      summary: get_all_products
      operationId: get_all_products
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/get_all_tags:
    get:
      tags:
      - Misc
      summary: get_all_tags
      operationId: get_all_tags
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
tags:
- name: Misc
  description: ''