openapi: 3.0.0
info:
  title: ShadowFax
  contact: {}
  version: '1.0'
servers:
- url: https://api.chetanpareek.tech
  variables: {}
- url: https://api.chetanpareek.tech/
  variables: {}
paths:
  /:
    get:
      tags:
      - Misc
      summary: home route
      operationId: homeroute
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://api.chetanpareek.tech
        variables: {}
  /api/get_all_products:
    get:
      tags:
      - Misc
      summary: get_all_products
      operationId: get_all_products
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://api.chetanpareek.tech
        variables: {}
  /api/get_all_tags:
    get:
      tags:
      - Misc
      summary: get_all_tags
      operationId: get_all_tags
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://api.chetanpareek.tech
        variables: {}
  /get_product_using_inc_id:
    get:
      tags:
      - Misc
      summary: get_products_using_inc_id
      operationId: get_products_using_inc_id
      parameters:
      - name: inc_id
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 21
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://api.chetanpareek.tech/api
        variables: {}
tags:
- name: Misc
  description: ''